=== fancooling/mentorpi/ubuntu_tank/config/sros2/schemas/omg_shared_ca_permissions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Official OMG DDS-Security permissions XSD schema specification for SROS2 validation.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="dds" type="PermissionsNode" />
    <xs:complexType name="PermissionsNode">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="permissions" type="Permissions" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Permissions">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="grant" type="Grant" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Grant">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="subject_name" type="xs:string" />
            <xs:element name="validity" type="Validity" />
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:choice minOccurs="1" maxOccurs="1">
                    <xs:element name="allow_rule" minOccurs="0" type="Rule" />
                    <xs:element name="deny_rule" minOccurs="0" type="Rule" />
                </xs:choice>
            </xs:sequence>
            <xs:element name="default" type="DefaultAction" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="Validity">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="not_before" type="xs:dateTime" />
            <xs:element name="not_after" type="xs:dateTime" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Rule">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="domains" type="DomainIdSet" />
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="publish" type="Criteria" />
            </xs:sequence>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="subscribe" type="Criteria" />
            </xs:sequence>
             <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="relay" type="Criteria" />
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DomainIdSet">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="id" type="DomainId" />
            <xs:element name="id_range" type="DomainIdRange" />
        </xs:choice>
    </xs:complexType>

    <xs:simpleType name="DomainId">
        <xs:restriction base="xs:nonNegativeInteger" />
    </xs:simpleType>

    <xs:complexType name="DomainIdRange">
        <xs:choice> <!-- DDSSEC-134 -->
            <xs:sequence>
                <xs:element name="min" type="DomainId" />
                <xs:element name="max" type="DomainId" minOccurs="0" />
            </xs:sequence>
            <xs:element name="max" type="DomainId" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="Criteria">
        <xs:all minOccurs="1">
            <!-- DDSSEC11-56 -->
            <xs:element name="topics" minOccurs="1" type="TopicExpressionList" />
            <xs:element name="partitions" minOccurs="0" type="PartitionExpressionList" />
            <xs:element name="data_tags" minOccurs="0" type="DataTags" />
        </xs:all>
    </xs:complexType>

    <xs:complexType name="TopicExpressionList">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="topic" type="TopicExpression" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PartitionExpressionList">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="partition" type="PartitionExpression" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="TopicExpression">
        <xs:restriction base="xs:string" />
    </xs:simpleType>

    <xs:simpleType name="PartitionExpression">
        <xs:restriction base="xs:string" />
    </xs:simpleType>

    <xs:complexType name="DataTags">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="tag" type="TagNameValuePair" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TagNameValuePair">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="name" type="xs:string" />
            <xs:element name="value" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="DefaultAction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ALLOW" />
            <xs:enumeration value="DENY" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== fancooling/mentorpi/ubuntu_tank/config/sros2/permissions/status_permissions.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
DDS Security permissions XML for read-only status monitor enclave
-->
<dds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="http://www.omg.org/spec/DDS-SECURITY/20170901/omg_shared_ca_permissions.xsd">
  <permissions>
    <grant name="/ubuntu_tank/status">
      <subject_name>CN=/ubuntu_tank/status</subject_name>
      <validity>
        <not_before>2026-01-01T00:00:00</not_before>
        <not_after>2036-01-01T00:00:00</not_after>
      </validity>
      <allow_rule>
        <domains>
          <id>0</id>
        </domains>
        <publish>
          <topics>
            <topic>ros_discovery_info</topic>
            <topic>rt/rosout</topic>
            <topic>rt/parameter_events</topic>
            <topic>rr/status_client/*Reply</topic>
            <topic>rr/_ros2cli_direct*/*Reply</topic>
          </topics>
        </publish>
        <subscribe>
          <topics>
            <topic>ros_discovery_info</topic>
            <topic>rt/ubuntu_tank_safety/state</topic>
            <topic>rt/ubuntu_tank_safety/armed</topic>
            <topic>rt/ros_robot_controller/battery</topic>
            <topic>rt/odom_raw</topic>
            <topic>rt/parameter_events</topic>
            <topic>rq/status_client/*Request</topic>
            <topic>rq/_ros2cli_direct*/*Request</topic>
          </topics>
        </subscribe>
      </allow_rule>
      <default>DENY</default>
    </grant>
  </permissions>
</dds>

=== fancooling/mentorpi/ubuntu_tank/config/sros2/permissions/bridge_permissions.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
DDS Security permissions XML for serial bridge enclave
-->
<dds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="http://www.omg.org/spec/DDS-SECURITY/20170901/omg_shared_ca_permissions.xsd">
  <permissions>
    <grant name="/ubuntu_tank/bridge">
      <subject_name>CN=/ubuntu_tank/bridge</subject_name>
      <validity>
        <not_before>2026-01-01T00:00:00</not_before>
        <not_after>2036-01-01T00:00:00</not_after>
      </validity>
      <allow_rule>
        <domains>
          <id>0</id>
        </domains>
        <publish>
          <topics>
            <topic>ros_discovery_info</topic>
            <topic>rt/ros_robot_controller/battery</topic>
            <topic>rt/ubuntu_tank/delivery_observation</topic>
            <topic>rt/rosout</topic>
            <topic>rt/parameter_events</topic>
            <topic>rr/ros_robot_controller/*Reply</topic>
          </topics>
        </publish>
        <subscribe>
          <topics>
            <topic>ros_discovery_info</topic>
            <topic>rt/ros_robot_controller/set_motor_guarded</topic>
            <topic>rt/parameter_events</topic>
            <topic>rq/ros_robot_controller/*Request</topic>
          </topics>
        </subscribe>
      </allow_rule>
      <default>DENY</default>
    </grant>
  </permissions>
</dds>

=== fancooling/mentorpi/ubuntu_tank/config/sros2/permissions/guard_permissions.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
DDS Security permissions XML for motor guard enclave
-->
<dds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="http://www.omg.org/spec/DDS-SECURITY/20170901/omg_shared_ca_permissions.xsd">
  <permissions>
    <grant name="/ubuntu_tank/guard">
      <subject_name>CN=/ubuntu_tank/guard</subject_name>
      <validity>
        <not_before>2026-01-01T00:00:00</not_before>
        <not_after>2036-01-01T00:00:00</not_after>
      </validity>
      <allow_rule>
        <domains>
          <id>0</id>
        </domains>
        <publish>
          <topics>
            <topic>ros_discovery_info</topic>
            <topic>rt/ros_robot_controller/set_motor_guarded</topic>
            <topic>rt/ubuntu_tank_safety/state</topic>
            <topic>rt/ubuntu_tank_safety/armed</topic>
            <topic>rt/rosout</topic>
            <topic>rt/parameter_events</topic>
            <topic>rr/ubuntu_tank_safety/set_armReply</topic>
            <topic>rr/motor_guard/*Reply</topic>
          </topics>
        </publish>
        <subscribe>
          <topics>
            <topic>ros_discovery_info</topic>
            <topic>rt/ubuntu_tank_safety/motor_input</topic>
            <topic>rt/parameter_events</topic>
            <topic>rq/ubuntu_tank_safety/set_armRequest</topic>
            <topic>rq/motor_guard/*Request</topic>
          </topics>
        </subscribe>
      </allow_rule>
      <default>DENY</default>
    </grant>
  </permissions>
</dds>

=== fancooling/mentorpi/ubuntu_tank/config/sros2/permissions/operator_permissions.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
DDS Security permissions XML for operator enclave
-->
<dds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="http://www.omg.org/spec/DDS-SECURITY/20170901/omg_shared_ca_permissions.xsd">
  <permissions>
    <grant name="/ubuntu_tank/operator">
      <subject_name>CN=/ubuntu_tank/operator</subject_name>
      <validity>
        <not_before>2026-01-01T00:00:00</not_before>
        <not_after>2036-01-01T00:00:00</not_after>
      </validity>
      <allow_rule>
        <domains>
          <id>0</id>
        </domains>
        <publish>
          <topics>
            <topic>ros_discovery_info</topic>
            <topic>rt/controller/cmd_vel</topic>
            <topic>rt/rosout</topic>
            <topic>rt/parameter_events</topic>
            <topic>rq/ubuntu_tank_safety/set_armRequest</topic>
            <topic>rr/teleop_key/*Reply</topic>
            <topic>rr/operator_client/*Reply</topic>
            <topic>rr/_ros2cli_requester_*/*Reply</topic>
          </topics>
        </publish>
        <subscribe>
          <topics>
            <topic>ros_discovery_info</topic>
            <topic>rt/ubuntu_tank_safety/state</topic>
            <topic>rt/ubuntu_tank_safety/armed</topic>
            <topic>rt/parameter_events</topic>
            <topic>rr/ubuntu_tank_safety/set_armReply</topic>
            <topic>rq/teleop_key/*Request</topic>
            <topic>rq/operator_client/*Request</topic>
            <topic>rq/_ros2cli_requester_*/*Request</topic>
          </topics>
        </subscribe>
      </allow_rule>
      <default>DENY</default>
    </grant>
  </permissions>
</dds>

=== fancooling/mentorpi/ubuntu_tank/config/sros2/permissions/controller_permissions.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
DDS Security permissions XML for controller enclave
-->
<dds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="http://www.omg.org/spec/DDS-SECURITY/20170901/omg_shared_ca_permissions.xsd">
  <permissions>
    <grant name="/ubuntu_tank/controller">
      <subject_name>CN=/ubuntu_tank/controller</subject_name>
      <validity>
        <not_before>2026-01-01T00:00:00</not_before>
        <not_after>2036-01-01T00:00:00</not_after>
      </validity>
      <allow_rule>
        <domains>
          <id>0</id>
        </domains>
        <publish>
          <topics>
            <topic>ros_discovery_info</topic>
            <topic>rt/ubuntu_tank_safety/motor_input</topic>
            <topic>rt/odom_raw</topic>
            <topic>rt/rosout</topic>
            <topic>rt/parameter_events</topic>
            <topic>rr/controller/*Reply</topic>
          </topics>
        </publish>
        <subscribe>
          <topics>
            <topic>ros_discovery_info</topic>
            <topic>rt/controller/cmd_vel</topic>
            <topic>rt/parameter_events</topic>
            <topic>rq/controller/*Request</topic>
          </topics>
        </subscribe>
      </allow_rule>
      <default>DENY</default>
    </grant>
  </permissions>
</dds>
